### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by danielbuechele** [comment]
Help me understand, what does this change do? Which node version is selected by Travis? 8 or 10? Is there any reason to use 10 as long as 8 is still LTS?

**Comment by DanielRuf** [comment]
Weird, normally Travis Ci should run two jobs. One for Node.js 8 and one for Node.js 10.

**Comment by DanielRuf** [comment]
10 is current stable and there were changes between 8 and 10 and many use 10 so it makes sense to test both. I saw many projects were the project failed on Node.js 10 due to specific dependencies which were not compatible or other code related changes.

**Comment by DanielRuf** [comment]
I'll adjust the build matrix.

**Comment by DanielRuf** [comment]
Looks better now =)

**Pull request closed without merging**
